<?php

namespace Paint\CheckboxFiscalization\Domain;

defined('ABSPATH') || exit;

final class CommandValidator
{
    /** @return array<string,mixed> */
    public function normalize(array $input): array
    {
        $schema = $this->string($input, 'schema_version', 8);
        if ($schema !== '1.0') {
            $this->fail('unsupported_schema', 'schema_version', 'Only schema_version 1.0 is supported.');
        }

        $operation_key = $this->string($input, 'operation_key', 191);
        if (!preg_match('/^[A-Za-z0-9][A-Za-z0-9._:-]{0,190}$/', $operation_key)) {
            $this->fail('invalid_operation_key', 'operation_key', 'The operation key contains unsupported characters.');
        }

        $receipt_id = strtolower($this->string($input, 'receipt_id', 36));
        if (!$this->isUuid($receipt_id)) {
            $this->fail('invalid_uuid', 'receipt_id', 'receipt_id must be a UUID generated by the caller.');
        }

        $operation_type = strtoupper($this->string($input, 'operation_type', 16));
        if (!in_array($operation_type, ['SELL', 'RETURN'], true)) {
            $this->fail('invalid_operation_type', 'operation_type', 'operation_type must be SELL or RETURN.');
        }

        $source_input = $input['source'] ?? null;
        if (!is_array($source_input)) {
            $this->fail('required', 'source', 'source is required.');
        }
        $source = [
            'system' => $this->string($source_input, 'system', 64, 'source.system'),
            'entity_type' => $this->string($source_input, 'entity_type', 64, 'source.entity_type'),
            'entity_id' => $this->string($source_input, 'entity_id', 191, 'source.entity_id'),
        ];
        if (isset($source_input['document_number']) && $source_input['document_number'] !== '') {
            $source['document_number'] = $this->limitedString($source_input['document_number'], 64, 'source.document_number');
        }
        if (isset($source_input['occurred_at']) && $source_input['occurred_at'] !== '') {
            $source['occurred_at'] = $this->isoDate($source_input['occurred_at'], 'source.occurred_at');
        }

        $currency = strtoupper((string) ($input['currency'] ?? 'UAH'));
        if ($currency !== 'UAH') {
            $this->fail('unsupported_currency', 'currency', 'Only UAH is supported by this connector.');
        }

        $expected_total = $this->positiveInt($input['expected_total_cents'] ?? null, 'expected_total_cents');
        $goods = $this->goods($input['goods'] ?? null, $operation_type);
        $payments = $this->payments($input['payments'] ?? null);
        $receipt_discounts = $this->discounts($input['discounts'] ?? [], 'discounts');

        $goods_total = array_sum(array_column($goods, 'line_total_cents'));
        $payments_total = array_sum(array_column($payments, 'value_cents'));
        if ($goods_total !== $expected_total) {
            $this->fail('goods_total_mismatch', 'expected_total_cents', 'The sum of goods line_total_cents must equal expected_total_cents.');
        }
        if ($payments_total !== $expected_total) {
            $this->fail('payments_total_mismatch', 'payments', 'The sum of payment values must equal expected_total_cents.');
        }

        $result = [
            'schema_version' => '1.0',
            'operation_key' => $operation_key,
            'receipt_id' => $receipt_id,
            'operation_type' => $operation_type,
            'source' => $source,
            'currency' => 'UAH',
            'expected_total_cents' => $expected_total,
            'goods' => $goods,
            'payments' => $payments,
            'discounts' => $receipt_discounts,
        ];

        foreach (['cashier_name' => 128, 'department' => 128, 'control_number' => 4, 'header' => 1024, 'footer' => 1024, 'barcode' => 4096, 'stock_code' => 128] as $field => $max) {
            if (isset($input[$field]) && $input[$field] !== '') {
                $result[$field] = $this->limitedString($input[$field], $max, $field);
            }
        }
        foreach (['order_id', 'previous_receipt_id'] as $field) {
            if (isset($input[$field]) && $input[$field] !== '') {
                $uuid = strtolower($this->limitedString($input[$field], 36, $field));
                if (!$this->isUuid($uuid)) {
                    $this->fail('invalid_uuid', $field, $field . ' must be a UUID.');
                }
                $result[$field] = $uuid;
            }
        }
        if (array_key_exists('technical_return', $input)) {
            $result['technical_return'] = $this->boolean($input['technical_return'], 'technical_return');
        }
        if (isset($input['context'])) {
            $result['context'] = $this->context($input['context']);
        }

        $rounding_mode = $input['rounding_mode'] ?? null;
        if ($rounding_mode !== null && $rounding_mode !== '') {
            $rounding_mode = strtoupper($this->limitedString($rounding_mode, 16, 'rounding_mode'));
            if (!in_array($rounding_mode, ['ROUND_10', 'ROUND_50'], true)) {
                $this->fail('invalid_rounding_mode', 'rounding_mode', 'rounding_mode must be ROUND_10 or ROUND_50.');
            }
            $result['rounding_mode'] = $rounding_mode;
        }

        if ($operation_type === 'RETURN') {
            $related = strtolower($this->limitedString($input['related_receipt_id'] ?? '', 36, 'related_receipt_id'));
            if (!$this->isUuid($related)) {
                $this->fail('invalid_related_receipt', 'related_receipt_id', 'A return requires the original Checkbox receipt UUID.');
            }
            $result['related_receipt_id'] = $related;
        }

        if (isset($input['delivery']) && $input['delivery'] !== null) {
            $result['delivery'] = $this->delivery($input['delivery']);
        }

        return $result;
    }

    /** @param array<string,mixed> $command */
    public function hash(array $command): string
    {
        $copy = $command;
        $this->sortRecursive($copy);
        return hash('sha256', wp_json_encode($copy, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    }

    /** @return list<array<string,mixed>> */
    private function goods(mixed $value, string $operation_type): array
    {
        if (!is_array($value) || $value === [] || count($value) > 1000) {
            $this->fail('invalid_goods', 'goods', 'goods must contain between 1 and 1000 items.');
        }

        $result = [];
        foreach (array_values($value) as $index => $raw) {
            $path = 'goods.' . $index;
            if (!is_array($raw)) {
                $this->fail('invalid_good', $path, 'Each goods item must be an object.');
            }
            $item = [
                'code' => $this->string($raw, 'code', 256, $path . '.code'),
                'name' => $this->string($raw, 'name', 512, $path . '.name'),
                'price_cents' => $this->nonNegativeInt($raw['price_cents'] ?? null, $path . '.price_cents'),
                'quantity_thousandths' => $this->positiveInt($raw['quantity_thousandths'] ?? null, $path . '.quantity_thousandths'),
                'line_total_cents' => $this->positiveInt($raw['line_total_cents'] ?? null, $path . '.line_total_cents'),
                'tax_codes' => $this->taxCodes($raw['tax_codes'] ?? null, $path . '.tax_codes'),
                'discounts' => $this->discounts($raw['discounts'] ?? [], $path . '.discounts'),
                'is_return' => $operation_type === 'RETURN',
            ];
            foreach (['barcode' => 4096, 'uktzed' => 64, 'header' => 1024, 'footer' => 1024] as $field => $max) {
                if (isset($raw[$field]) && $raw[$field] !== '') {
                    $item[$field] = $this->limitedString($raw[$field], $max, $path . '.' . $field);
                }
            }
            if (isset($raw['excise_barcodes'])) {
                if (!is_array($raw['excise_barcodes']) || count($raw['excise_barcodes']) > 100) {
                    $this->fail('invalid_excise_barcodes', $path . '.excise_barcodes', 'excise_barcodes must be an array.');
                }
                $item['excise_barcodes'] = array_map(
                    fn ($barcode) => $this->limitedString($barcode, 4096, $path . '.excise_barcodes'),
                    array_values($raw['excise_barcodes'])
                );
            }
            $result[] = $item;
        }
        return $result;
    }

    /** @return list<array<string,mixed>> */
    private function payments(mixed $value): array
    {
        if (!is_array($value) || $value === [] || count($value) > 10) {
            $this->fail('invalid_payments', 'payments', 'payments must contain between 1 and 10 entries.');
        }
        $result = [];
        foreach (array_values($value) as $index => $raw) {
            $path = 'payments.' . $index;
            if (!is_array($raw)) {
                $this->fail('invalid_payment', $path, 'Each payment must be an object.');
            }
            $type = strtoupper($this->string($raw, 'type', 16, $path . '.type'));
            if (!in_array($type, ['CASH', 'CASHLESS'], true)) {
                $this->fail('invalid_payment_type', $path . '.type', 'Payment type must be CASH or CASHLESS.');
            }
            $payment = [
                'type' => $type,
                'value_cents' => $this->positiveInt($raw['value_cents'] ?? null, $path . '.value_cents'),
                'label' => $this->limitedString($raw['label'] ?? ($type === 'CASH' ? 'Готівка' : 'Картка'), 128, $path . '.label'),
            ];
            if ($type === 'CASHLESS') {
                $code = isset($raw['code']) ? $this->nonNegativeInt($raw['code'], $path . '.code') : 1;
                if ($code < 1 || $code > 9) {
                    $this->fail('invalid_payment_code', $path . '.code', 'Cashless payment code must be between 1 and 9.');
                }
                $payment['code'] = $code;
                foreach (['provider_type' => 64, 'card_mask' => 19, 'bank_name' => 128, 'auth_code' => 64, 'rrn' => 64, 'payment_system' => 64, 'owner_name' => 128, 'terminal' => 128, 'acquirer_and_seller' => 256, 'receipt_no' => 64, 'transaction_id' => 128] as $field => $max) {
                    if (isset($raw[$field]) && $raw[$field] !== '') {
                        $payment[$field] = $this->limitedString($raw[$field], $max, $path . '.' . $field);
                    }
                }
                if (isset($raw['commission'])) {
                    $payment['commission'] = $this->nonNegativeInt($raw['commission'], $path . '.commission');
                }
                if (array_key_exists('signature_required', $raw)) {
                    $payment['signature_required'] = $this->boolean($raw['signature_required'], $path . '.signature_required');
                }
                if (isset($raw['tapxphone_terminal']) && $raw['tapxphone_terminal'] !== '') {
                    $terminal_id = strtolower($this->limitedString($raw['tapxphone_terminal'], 36, $path . '.tapxphone_terminal'));
                    if (!$this->isUuid($terminal_id)) {
                        $this->fail('invalid_uuid', $path . '.tapxphone_terminal', 'tapxphone_terminal must be a UUID.');
                    }
                    $payment['tapxphone_terminal'] = $terminal_id;
                }
            }
            $result[] = $payment;
        }
        return $result;
    }

    /** @return list<array<string,mixed>> */
    private function discounts(mixed $value, string $path): array
    {
        if (!is_array($value) || count($value) > 100) {
            $this->fail('invalid_discounts', $path, 'discounts must be an array with at most 100 entries.');
        }
        $result = [];
        foreach (array_values($value) as $index => $raw) {
            $item_path = $path . '.' . $index;
            if (!is_array($raw)) {
                $this->fail('invalid_discount', $item_path, 'Each discount must be an object.');
            }
            $type = strtoupper($this->string($raw, 'type', 16, $item_path . '.type'));
            $mode = strtoupper($this->string($raw, 'mode', 16, $item_path . '.mode'));
            if (!in_array($type, ['DISCOUNT', 'EXTRA_CHARGE'], true)) {
                $this->fail('invalid_discount_type', $item_path . '.type', 'Discount type must be DISCOUNT or EXTRA_CHARGE.');
            }
            if (!in_array($mode, ['VALUE', 'PERCENT'], true)) {
                $this->fail('invalid_discount_mode', $item_path . '.mode', 'Discount mode must be VALUE or PERCENT.');
            }
            $discount = [
                'type' => $type,
                'mode' => $mode,
                'value' => $mode === 'VALUE'
                    ? $this->positiveInt($raw['value'] ?? null, $item_path . '.value')
                    : $this->positiveNumber($raw['value'] ?? null, $item_path . '.value'),
            ];
            if (isset($raw['name']) && $raw['name'] !== '') {
                $discount['name'] = $this->limitedString($raw['name'], 128, $item_path . '.name');
            }
            if (isset($raw['tax_codes'])) {
                $discount['tax_codes'] = $this->taxCodes($raw['tax_codes'], $item_path . '.tax_codes');
            }
            $result[] = $discount;
        }
        return $result;
    }

    /** @return list<int|string> */
    private function taxCodes(mixed $value, string $path): array
    {
        if (!is_array($value) || $value === [] || count($value) > 16) {
            $this->fail('invalid_tax_codes', $path, 'Every goods item must provide at least one Checkbox tax code.');
        }
        $result = [];
        foreach (array_values($value) as $code) {
            if (is_int($code) || (is_string($code) && preg_match('/^[A-Za-z0-9._-]{1,32}$/', $code))) {
                $result[] = $code;
                continue;
            }
            $this->fail('invalid_tax_code', $path, 'Tax codes must be integers or short code strings.');
        }
        return $result;
    }

    /** @return array<string,mixed> */
    private function delivery(mixed $value): array
    {
        if (!is_array($value)) {
            $this->fail('invalid_delivery', 'delivery', 'delivery must be an object.');
        }
        $result = [];
        if (isset($value['email']) && $value['email'] !== '') {
            $email = $this->limitedString($value['email'], 254, 'delivery.email');
            if (!is_email($email)) {
                $this->fail('invalid_email', 'delivery.email', 'delivery.email is invalid.');
            }
            $result['email'] = $email;
        }
        if (isset($value['phone']) && $value['phone'] !== '') {
            $phone = $this->limitedString($value['phone'], 32, 'delivery.phone');
            if (!preg_match('/^\+?380[0-9]{9}$/', $phone)) {
                $this->fail('invalid_phone', 'delivery.phone', 'delivery.phone must be a Ukrainian number in +380XXXXXXXXX format.');
            }
            $result['phone'] = $phone;
        }
        if (isset($value['emails'])) {
            if (!is_array($value['emails']) || $value['emails'] === [] || count($value['emails']) > 10) {
                $this->fail('invalid_emails', 'delivery.emails', 'delivery.emails must contain between 1 and 10 addresses.');
            }
            $result['emails'] = [];
            foreach (array_values($value['emails']) as $index => $raw_email) {
                $email = $this->limitedString($raw_email, 254, 'delivery.emails.' . $index);
                if (!is_email($email)) {
                    $this->fail('invalid_email', 'delivery.emails.' . $index, 'delivery.emails contains an invalid address.');
                }
                $result['emails'][] = $email;
            }
            $result['emails'] = array_values(array_unique($result['emails']));
        }
        if ($result === []) {
            $this->fail('empty_delivery', 'delivery', 'delivery must contain a valid email or phone.');
        }
        return $result;
    }

    private function string(array $data, string $field, int $max, ?string $path = null): string
    {
        if (!array_key_exists($field, $data) || $data[$field] === '') {
            $this->fail('required', $path ?? $field, ($path ?? $field) . ' is required.');
        }
        return $this->limitedString($data[$field], $max, $path ?? $field);
    }

    private function limitedString(mixed $value, int $max, string $path): string
    {
        if (!is_scalar($value)) {
            $this->fail('invalid_string', $path, $path . ' must be a string.');
        }
        $value = trim((string) $value);
        $length = function_exists('mb_strlen') ? mb_strlen($value) : strlen($value);
        if ($value === '' || $length > $max) {
            $this->fail('invalid_length', $path, $path . ' is empty or too long.');
        }
        return $value;
    }

    private function positiveInt(mixed $value, string $path): int
    {
        $number = $this->integer($value, $path);
        if ($number <= 0) {
            $this->fail('not_positive', $path, $path . ' must be greater than zero.');
        }
        return $number;
    }

    private function nonNegativeInt(mixed $value, string $path): int
    {
        $number = $this->integer($value, $path);
        if ($number < 0) {
            $this->fail('negative', $path, $path . ' must not be negative.');
        }
        return $number;
    }

    private function positiveNumber(mixed $value, string $path): int|float
    {
        if (!is_int($value) && !is_float($value) && !(is_string($value) && is_numeric($value))) {
            $this->fail('invalid_number', $path, $path . ' must be numeric.');
        }
        $number = (float) $value;
        if (!is_finite($number) || $number <= 0) {
            $this->fail('not_positive', $path, $path . ' must be greater than zero.');
        }
        return floor($number) === $number ? (int) $number : $number;
    }

    private function boolean(mixed $value, string $path): bool
    {
        if (!is_bool($value)) {
            $this->fail('invalid_boolean', $path, $path . ' must be true or false.');
        }
        return $value;
    }

    /** @return array<string,int|float|string|bool> */
    private function context(mixed $value): array
    {
        if (!is_array($value) || array_is_list($value) || count($value) > 50) {
            $this->fail('invalid_context', 'context', 'context must be an object with at most 50 scalar fields.');
        }
        $result = [];
        foreach ($value as $key => $item) {
            $key = $this->limitedString($key, 64, 'context key');
            if (is_string($item)) {
                $result[$key] = $this->limitedString($item, 256, 'context.' . $key);
            } elseif (is_int($item) || is_float($item) || is_bool($item)) {
                $result[$key] = $item;
            } else {
                $this->fail('invalid_context_value', 'context.' . $key, 'Context values must be scalar JSON values.');
            }
        }
        return $result;
    }

    private function integer(mixed $value, string $path): int
    {
        if (!is_int($value) && !(is_string($value) && preg_match('/^-?[0-9]+$/', $value))) {
            $this->fail('invalid_integer', $path, $path . ' must be an integer.');
        }
        return (int) $value;
    }

    private function isoDate(mixed $value, string $path): string
    {
        $value = $this->limitedString($value, 40, $path);
        try {
            return (new \DateTimeImmutable($value))->format(DATE_ATOM);
        } catch (\Throwable) {
            $this->fail('invalid_datetime', $path, $path . ' must be an ISO-8601 date-time.');
        }
    }

    private function isUuid(string $value): bool
    {
        return (bool) preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $value);
    }

    private function sortRecursive(array &$value): void
    {
        foreach ($value as &$item) {
            if (is_array($item)) {
                $this->sortRecursive($item);
            }
        }
        unset($item);
        if (!array_is_list($value)) {
            ksort($value);
        }
    }

    private function fail(string $code, string $path, string $message): never
    {
        throw new ValidationException($code, $path, $message);
    }
}
