<?php
/** Included by telegram.php under local fixtures and mocked network. */
use PaintCore\PCOE\ConversationStore as Chat;
use PaintCore\PCOE\CustomerManagers as Team;
use PaintCore\PCOE\TelegramManagers as Staff;
use PaintCore\PCOE\TelegramStore as Store;
use PaintCore\PCOE\TelegramBridge as Bridge;
if (!defined('WP_CLI') || !WP_CLI || !isset($check,$bind) || wp_parse_url(home_url(),PHP_URL_HOST)!=='paint.local') throw new RuntimeException('Run through local telegram.php');
foreach (['customer','shop_manager'] as $i=>$role) {
 $id=wp_insert_user(['user_login'=>'tg-pair-'.wp_generate_uuid4(),'user_pass'=>wp_generate_password(30),'user_email'=>'tg-pair-'.wp_generate_uuid4().'@example.invalid','role'=>$role]);
 if(is_wp_error($id))throw new RuntimeException('Team fixture');$users[]=$id;
 if(!$i)$teamCustomer=$id;else $third=$id;
}
$teamPeer='700000000005';$thirdPeer='700000000006';$bind($teamCustomer,$teamPeer);$bind($third,$thirdPeer);
wp_set_current_user($teamCustomer);$denied(fn()=>Team::save($teamCustomer,$manager,$admin,'',false));
$existing=Chat::start($teamCustomer,0,'Existing open','Old question',wp_generate_uuid4());$threads[]=$existing;
$closed=Chat::start($teamCustomer,0,'Closed history','Closed question',wp_generate_uuid4());$threads[]=$closed;
wp_set_current_user($admin);$m=Chat::meta($closed);Chat::assign($closed,$third,'closed',$m['revision']);
$denied(fn()=>Team::save($teamCustomer,$manager,$manager,'',false));
$denied(fn()=>Team::save($teamCustomer,0,$admin,'',false));
$denied(fn()=>Team::save($teamCustomer,$manager,$teamCustomer,'',false));
$denied(fn()=>Team::save($third,$manager,$admin,'',false));
Team::save($teamCustomer,$manager,$admin,'',false);$team=Team::get($teamCustomer);
$check($team['primary']===$manager && $team['secondary']===$admin && $team['revision']!=='','Customer card saves pair with revision');
$check(Chat::meta($existing)['assignee']===0 && Chat::meta($closed)['assignee']===$third,'Defaults alone preserve open and closed existing assignments');
$denied(fn()=>Team::save($teamCustomer,$admin,$manager,'',false));
wp_set_current_user($teamCustomer);$paired=Chat::start($teamCustomer,0,'Paired topic','Customer to both',wp_generate_uuid4());$threads[]=$paired;$first=Chat::latest($paired);
$check(Chat::meta($paired)['assignee']===$manager && Chat::meta($paired)['secondary']===$admin,'New customer conversation inherits both managers');
$job1='manager-message:'.$first.':'.$manager.':0';$job2='manager-message:'.$first.':'.$admin.':0';
$check(Store::get($job1)!==null && Store::get($job2)!==null && Store::get('manager-message:'.$first.':'.$third.':0')===null,'Paired message goes to both assigned managers only');
Bridge::deliver($job1);$primaryMessage=$sent;Bridge::deliver($job2);$secondaryMessage=$sent;
$check(Store::get($job1)['status']==='sent' && Store::get($job2)['status']==='sent','Both pair members receive the customer message');
wp_set_current_user($third);$madeByThird=Chat::start($teamCustomer,0,'Created by other staff','Staff opens',wp_generate_uuid4());$threads[]=$madeByThird;
$check(Chat::meta($madeByThird)['assignee']===$manager && Chat::meta($madeByThird)['secondary']===$admin,'Customer defaults win over the creator of a new conversation');
wp_set_current_user($admin);$check(in_array($paired,wp_list_pluck(Chat::listing('mine',1,$teamCustomer)->posts,'ID'),true),'Additional manager sees thread in Mine on website');
$cmd=$incoming('/threads',$adminPeer);$send($cmd);$check(Store::get('manager-list:update:'.$bot.':'.$cmd['update_id'].':'.$paired.':'.$admin.':0')!==null,'Additional manager sees paired conversation in Telegram list');
$replyUpdate=$incoming('Deputy answers',$adminPeer,['reply_to_message'=>['message_id'=>$secondaryMessage]]);$send($replyUpdate);$reply=Chat::latest($paired);
$check((int)get_post($reply)->post_author===$admin && get_post_meta($reply,'_chat_actor',true)==='manager','Additional manager can reply in its own name');
$check(Chat::meta($paired)['assignee']===$manager && Chat::meta($paired)['secondary']===$admin,'Deputy reply does not replace responsible manager');
$colleague='manager-message:'.$reply.':'.$manager.':0';
$check(Store::get($colleague)!==null && Store::get('manager-message:'.$reply.':'.$admin.':0')===null,'Colleague receives reply, author receives no duplicate echo');
$check(str_contains(Store::get($colleague)['data']['payload']['text'],get_userdata($admin)->display_name),'Colleague notification identifies replying manager');
$check(Store::get('message:'.$reply.':0')!==null,'Deputy reply also reaches customer outbox');
$before=count(Chat::messages($paired)['messages']);$send($replyUpdate);$check(count(Chat::messages($paired)['messages'])===$before,'Repeated deputy webhook remains idempotent');
Bridge::deliver($colleague);$colleagueMessage=$sent;
$send($incoming('Primary follows up',$managerPeer,['reply_to_message'=>['message_id'=>$colleagueMessage]]));$reply=Chat::latest($paired);
$check((int)get_post($reply)->post_author===$manager && Store::get('manager-message:'.$reply.':'.$admin.':0')!==null,'Primary can reply to colleague notification and notifies deputy');
wp_set_current_user($manager);$siteReply=Chat::reply($paired,'Reply from website',false,wp_generate_uuid4());
$check(Store::get('manager-message:'.$siteReply.':'.$admin.':0')!==null,'Website replies also notify colleague');
$beforeJobs=Store::records('job',['pending'],1000);Chat::reply($paired,'Internal pair note',true,wp_generate_uuid4());
$check(Store::records('job',['pending'],1000)===$beforeJobs,'Internal notes never enter pair Telegram');
$m=Chat::meta($paired);$denied(fn()=>Chat::assign($paired,$manager,$m['state'],$m['revision'],$manager));
wp_set_current_user($admin);Team::save($teamCustomer,$manager,$third,$team['revision'],false);
$check(Chat::meta($paired)['secondary']===$admin,'Changing customer defaults alone preserves existing pair');
$t=Team::get($teamCustomer);Team::save($teamCustomer,$manager,$third,$t['revision'],true);
$check(Chat::meta($existing)['assignee']===$manager && Chat::meta($existing)['secondary']===$third && Chat::meta($paired)['secondary']===$third,'Explicit bulk application updates existing open conversations');
$check(Chat::meta($closed)['assignee']===$third && Chat::meta($closed)['secondary']===0 && Chat::meta($closed)['state']==='closed','Bulk application preserves closed conversations');
Bridge::deliver('manager-message:'.$siteReply.':'.$admin.':0');$check(Store::get('manager-message:'.$siteReply.':'.$admin.':0')['status']==='cancelled','Removed deputy queued notifications cancel');
$before=count(Chat::messages($paired)['messages']);$send($incoming('Removed deputy reply',$adminPeer,['reply_to_message'=>['message_id'=>$secondaryMessage]]));$check(count(Chat::messages($paired)['messages'])===$before,'Removed deputy cannot use old reply mapping');
$newContext='assignment:'.$paired.':'.Chat::meta($paired)['revision'].':'.$third.':0';Bridge::deliver($newContext);$thirdMessage=$sent;
$check(Store::get($newContext)['status']==='sent','Replacement deputy receives public conversation context');
$send($incoming('Replacement answers',$thirdPeer,['reply_to_message'=>['message_id'=>$thirdMessage]]));$check((int)get_post(Chat::latest($paired))->post_author===$third,'Replacement deputy can reply');
// Failure halfway through applying open assignments rolls back defaults, every assignment and outbox.
wp_set_current_user($admin);$oldTeam=Team::get($teamCustomer);$oldMeta=Chat::meta($paired);$oldExisting=Chat::meta($existing);$oldJobs=Store::records('job',['pending'],1000);
$fail=static function($id)use($paired){if($id===$paired)throw new RuntimeException('Pair bulk rollback');};add_action('pcoe_chat_assignment_saved',$fail,20);
$denied(fn()=>Team::save($teamCustomer,$admin,$manager,$oldTeam['revision'],true));remove_action('pcoe_chat_assignment_saved',$fail,20);
$check(Team::get($teamCustomer)===$oldTeam && Chat::meta($paired)===$oldMeta && Chat::meta($existing)===$oldExisting,'Bulk failure rolls back defaults and every thread, including caches');
$check(Store::records('job',['pending'],1000)===$oldJobs,'Bulk rollback also removes notification jobs');
// Individual thread editing does not rewrite customer defaults; secondary is preserved on state-only edits.
$m=Chat::meta($paired);Chat::assign($paired,$manager,'waiting_customer',$m['revision']);$check(Chat::meta($paired)['secondary']===$third,'Legacy state-only operation preserves additional manager');
$m=Chat::meta($paired);Chat::assign($paired,$admin,$m['state'],$m['revision']);$check(Chat::meta($paired)['secondary']===0 && Team::get($teamCustomer)===$oldTeam,'Changing primary via legacy call clears old deputy and leaves defaults intact');
wp_set_current_user($teamCustomer);$text=Chat::reply($existing,'Check live capabilities',false,wp_generate_uuid4());
(new WP_User($third))->set_role('customer');Bridge::deliver('manager-message:'.$text.':'.$third.':0');
$check(Store::get('manager-message:'.$text.':'.$third.':0')['status']==='cancelled' && !Staff::allowed($existing,$third),'Lost manager capability blocks additional manager immediately');
$fresh=Chat::start($teamCustomer,0,'Invalid deputy default','Question',wp_generate_uuid4());$threads[]=$fresh;
$check(Chat::meta($fresh)['assignee']===$manager && Chat::meta($fresh)['secondary']===0,'New thread omits deputy whose rights were removed');
(new WP_User($third))->set_role('shop_manager');
wp_set_current_user($admin);$t=Team::get($teamCustomer);Team::save($teamCustomer,0,0,$t['revision'],false);
wp_set_current_user($teamCustomer);$free=Chat::start($teamCustomer,0,'No defaults','Back to queue',wp_generate_uuid4());$threads[]=$free;
$check(Chat::meta($free)['assignee']===0 && Chat::meta($free)['secondary']===0,'Clearing defaults restores normal unassigned queue for future threads');
wp_set_current_user($admin);ob_start();Team::render($teamCustomer);$html=ob_get_clean();
$check(str_contains($html,'name="primary"') && str_contains($html,'name="secondary"') && str_contains($html,'name="apply_open"') && !str_contains($html,'value="1" checked'),'Customer team UI exposes two selectors and an opt-in bulk change');
wp_set_current_user($teamCustomer);$denied(fn()=>Team::render($teamCustomer));
wp_set_current_user($customer);
