const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
    const browser = await chromium.launch({executablePath:process.env.CHROME_BINARY || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
    try {
        const context = await browser.newContext();
        await context.route('**/*', route => ['paint.local','kreul-media.s3.gra.io.cloud.ovh.net'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
        const page = await context.newPage();
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.goto('http://paint.local/',{waitUntil:'domcontentloaded'});
        assert.equal(await page.locator('#psu-catalog-search').count(),1,'Home retains the unified search');
        for (const width of [1280,390]) {
            await page.setViewportSize({width,height:900});
            await page.goto('http://paint.local/category/laki/',{waitUntil:'domcontentloaded'});
            const input = page.locator('#psu-catalog-search');
            await input.waitFor();
            assert.equal(await page.locator('.wp-block-search__input').count(),0,'No duplicate sidebar search');
            const details = page.locator('.psu-catalog-filters__advanced');
            assert.equal(await details.getAttribute('open'),null,'Filters collapsed on both layouts');
            await details.locator('summary').click();
            await details.locator('[name="unit"]').selectOption({label:'250 мл'});
            await details.locator('summary').click();
            assert.equal(await details.locator('[name="unit"]').inputValue(),'250 мл','Collapsing preserves selection');
            await input.fill('KR-79406');
            const row = page.locator('#psu-search-options li');
            await row.first().waitFor({timeout:30000});
            assert.match(await row.first().innerText(),/KR-79406/);
            assert.match(await row.first().innerText(),/Киев|Київ|Одеса|Одесса/);
            await row.first().locator('img').evaluate(img => img.complete ? Promise.resolve() : new Promise(resolve => {img.onload=resolve;img.onerror=resolve;}));
            assert(await row.first().locator('img').evaluate(img => img.naturalWidth > 0),'Photo actually loads');
            await input.evaluate(el => window.scrollTo(0, window.scrollY + el.getBoundingClientRect().top - 220));
            await page.evaluate(() => new Promise(requestAnimationFrame));
            const box = await page.locator('.psu-search-suggestions').boundingBox();
            assert(box.y >= 0 && box.y + box.height <= 900,'Suggestions fit the viewport');
            await page.screenshot({path:'/tmp/psu-unified-search-'+width+'.png'});
            assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth+1),'No horizontal overflow');
            await input.press('ArrowDown');
            assert.equal(await input.getAttribute('aria-activedescendant'),'psu-search-option-0');
            await input.press('Escape');
            assert.equal(await input.getAttribute('aria-expanded'),'false');
            assert.equal(await input.inputValue(),'KR-79406','Escape closes suggestions without clearing the query');
            // Changing filters must not reuse an earlier result from a different scope.
            await details.locator('summary').click();
            await details.locator('[name="unit"]').selectOption({label:'125 мл'});
            await input.fill('KR-79406 ');
            await page.locator('.psu-search-status').filter({hasText:/No matching|не знайдено|не найдено/}).waitFor({timeout:30000});
            assert.equal(await row.count(),0,'Unit restricts suggestions');
            await details.locator('[name="unit"]').selectOption('');
            await input.fill('4000798794064');
            await row.first().waitFor({timeout:30000});
            assert.match(await row.first().innerText(),/KR-79406/,'Barcode is indexed');
            await input.press('ArrowDown');
            await input.press('Enter');
            await page.waitForURL('**/p/**');
        }
        // Endpoint errors leave the normal category search usable.
        await page.goto('http://paint.local/category/laki/',{waitUntil:'domcontentloaded'});
        await page.route('**/admin-ajax.php?action=psu_catalog_suggest*', route => route.fulfill({status:503,body:'Temporary failure'}));
        // action is last in the query; match the entire route with a predicate.
        await page.route(url => url.searchParams.get('action') === 'psu_catalog_suggest', route => route.fulfill({status:503,body:'Temporary failure'}));
        await page.locator('#psu-catalog-search').fill('KR-79406');
        await page.locator('.psu-search-status').filter({hasText:/unavailable|недоступ/}).waitFor({timeout:30000});
        await page.locator('#psu-catalog-search').press('Enter');
        await page.waitForURL(/catalog_search=KR-79406/);
        assert.match(page.url(),/product_cat=laki/,'Normal submit preserves category');
        assert(await page.locator('li.product').count(),'Normal search still returns products');
        await page.unrouteAll({behavior:'wait'});
        await page.locator('#psu-catalog-search').fill('лак');
        await page.waitForFunction(() => document.querySelectorAll('#psu-search-options li').length > 1);
        await page.locator('#psu-catalog-search').press('ArrowUp');
        assert.equal(await page.locator('#psu-catalog-search').getAttribute('aria-activedescendant'), 'psu-search-option-'+(await page.locator('#psu-search-options li').count()-1),'ArrowUp initially chooses the last result');
        await page.locator('#psu-catalog-search').fill('');
        assert.equal(await page.locator('#psu-catalog-search').getAttribute('aria-expanded'),'false','Clearing closes results');
        const nojs = await browser.newContext({javaScriptEnabled:false});
        const plain = await nojs.newPage();
        await plain.goto('http://paint.local/category/laki/',{waitUntil:'domcontentloaded'});
        await plain.locator('.psu-catalog-filters__advanced > summary').click();
        assert(await plain.locator('.psu-catalog-filters [name="unit"]').isVisible(),'Native filter toggle works without JS');
        await plain.locator('#psu-catalog-search').fill('KR-79406');
        await plain.locator('#psu-catalog-search').press('Enter');
        await plain.waitForURL(/catalog_search=KR-79406/);
        assert(await plain.locator('li.product').count(),'Search works without JS');
        await nojs.close();
        const fixture = JSON.parse(fs.readFileSync('/tmp/psu-search-session.json','utf8'));
        const wholesale = await browser.newContext();
        await wholesale.addCookies(fixture.cookies);
        const response = await wholesale.request.get('http://paint.local/wp-admin/admin-ajax.php?action=psu_catalog_suggest&catalog_search=KR-79406');
        assert.equal(response.status(),200);
        assert.match(response.headers()['cache-control'],/private/,'Personalized response stays private');
        assert.match(response.headers()['cache-control'],/no-store/,'Personalized response cannot enter shared caches');
        assert.equal((await response.json()).items[0].price,fixture.expected,'AJAX uses current customer price');
        await wholesale.route('**/*', route => ['paint.local','kreul-media.s3.gra.io.cloud.ovh.net'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
        const help = await wholesale.newPage();
        await help.setViewportSize({width:390,height:900});
        await help.goto('http://paint.local/category/laki/',{waitUntil:'domcontentloaded'});
        await help.locator('#psu-catalog-search').fill('KR-79406');
        await help.locator('#psu-search-options li').first().waitFor({timeout:30000});
        await help.locator('#psu-catalog-search').evaluate(el => window.scrollTo(0, window.scrollY + el.getBoundingClientRect().top - 160));
        await help.evaluate(() => new Promise(requestAnimationFrame));
        await help.screenshot({path:'/tmp/psu-unified-search-wholesale-mobile.png'});
        await help.locator('#psu-catalog-search').press('Escape');
        await help.locator('#psu-catalog-search').fill('');
        await help.screenshot({path:'/tmp/psu-unified-search-collapsed-mobile.png'});
        assert.equal(errors.length,0,errors.join('\n'));
        await wholesale.close(); await context.close();
        console.log(JSON.stringify({passed:true,desktopAndMobile:true,photoLoaded:true,keyboard:true,filterScope:true,barcode:true,errorFallback:true,wholesalePrice:true}));
    } finally { await browser.close(); }
})().catch(error => {console.error(error);process.exit(1);});
